# Generated by Django 6.0.2 on 2026-04-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
