# Generated by Django 6.0.2 on 2026-04-04 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0002_tiposervicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
