# Generated by Django 6.0.2 on 2026-04-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginVet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Producto',
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.TimeField()),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'db_table': 'tipo_servicio_cliente',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('especie', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], max_length=6)),
                ('raza', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('cantidad_visitas', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='loginVet.cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('estado_cita', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginVet.cliente')),
                ('id_veterinario', models.ForeignKey(db_column='id_veterinario', on_delete=django.db.models.deletion.RESTRICT, to='loginVet.veterinario')),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', null=True, on_delete=django.db.models.deletion.CASCADE, to='clienteApp.mascota')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clienteApp.tiposervicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('id_tipo_producto', models.ForeignKey(db_column='id_tipo_producto', on_delete=django.db.models.deletion.CASCADE, to='clienteApp.tipoproducto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo_consulta', models.CharField(blank=True, max_length=255)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(blank=True)),
                ('medicacion', models.CharField(blank=True, max_length=150)),
                ('frecuencia', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_cita', models.ForeignKey(db_column='id_cita', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clienteApp.cita')),
                ('id_veterinario', models.ForeignKey(db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginVet.veterinario')),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='clienteApp.mascota')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clienteApp.tiposervicio')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'db_table': 'historial_clinico',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('CARRITO', 'Carrito'), ('COMPLETADO', 'Completado')], default='CARRITO', max_length=15)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginVet.cliente')),
                ('id_vet', models.ForeignKey(db_column='id_vet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginVet.veterinario')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.RESTRICT, to='clienteApp.inventario')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='clienteApp.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_venta',
            },
        ),
    ]
