# Generated by Django 6.0.2 on 2026-06-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0003_tiposervicio_actualizado_el_tiposervicio_creado_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
