# Generated by Django 6.0.2 on 2026-04-02 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienteApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='clienteApp.inventario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Producto',
                'db_table': 'entrada_producto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('BAJA', 'Baja por vencimiento'), ('PERDIDA', 'Pérdida o robo'), ('DANO', 'Producto dañado'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='clienteApp.inventario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida de Producto',
                'db_table': 'salida_producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
