# Generated by Django 6.0.2 on 2026-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginVet', '0002_usuario_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_doc',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT')], default='CC', max_length=3),
        ),
    ]
