# Generated by Django 6.0.2 on 2026-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginVet', '0003_alter_usuario_tipo_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
