# Generated by Django 6.0.2 on 2026-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginVet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
